# Generated by Django 3.2.16 on 2022-12-13 11:37

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('academy', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=350)),
                ('training_hours', models.IntegerField()),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(limit_choices_to={'is_psychologist': True}, on_delete=django.db.models.deletion.CASCADE, related_name='specialty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_company', models.IntegerField()),
                ('experience_online', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('full_experience', models.IntegerField()),
                ('client', models.IntegerField()),
                ('time', models.IntegerField()),
                ('therapy', models.CharField(max_length=250)),
                ('therapy_hours', models.IntegerField(blank=True, null=True)),
                ('therapy_approach', models.CharField(max_length=350)),
                ('chat', models.CharField(max_length=250)),
                ('chat_hours', models.IntegerField(blank=True, null=True)),
                ('supervisor', models.CharField(max_length=350)),
                ('user', models.ForeignKey(limit_choices_to={'is_psychologist': True}, on_delete=django.db.models.deletion.CASCADE, related_name='pro_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=600)),
                ('faculty', models.CharField(max_length=600)),
                ('specialty', models.CharField(max_length=600)),
                ('degree', models.CharField(max_length=500)),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('diplom', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(limit_choices_to={'is_psychologist': True}, on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('salary', models.IntegerField()),
                ('other_job', models.CharField(max_length=50)),
                ('job_time', models.IntegerField()),
                ('about_me', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'is_psychologist': True}, on_delete=django.db.models.deletion.CASCADE, related_name='add_ques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
