# Generated by Django 3.2.16 on 2022-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=600)),
                ('faculty', models.CharField(max_length=600)),
                ('specialty', models.CharField(max_length=600)),
                ('degree', models.CharField(max_length=500)),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('diplom', models.FileField(upload_to='')),
            ],
        ),
    ]
