# Generated by Django 3.2.16 on 2022-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
    ]
