# Generated by Django 3.2.16 on 2022-12-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='webinars')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('tags', models.ManyToManyField(related_name='webinar', to='blog.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='webinar.webinar')),
            ],
        ),
    ]
