# Generated by Django 3.2.16 on 2022-12-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('validity_period', models.CharField(max_length=5)),
                ('cvv', models.IntegerField()),
                ('card_holder', models.CharField(max_length=250)),
            ],
        ),
    ]
