# Generated by Django 3.2.16 on 2022-12-09 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message="Card number must be entered in the format: '[XXXX] [XXXX] [XXXX] [XXXX]'. Up to 16 digits allowed.", regex='[0-9]{16}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='validity_period',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message="Validity period number must be entered in the format: '[XX]/[XX]. Up to 4 digits allowed.", regex='^[0-9]/[0-9]{4}$')]),
        ),
    ]
